# Generated by Django 2.2.12 on 2020-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndmain', '0002_auto_20200622_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
        ),
    ]
