# Generated by Django 2.2.12 on 2020-07-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndmain', '0004_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='party',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='dndmain.Party'),
        ),
    ]
